export const products = [
  {
    id: 'prod-1',
    organizationId: '111',
    name: 'Prod 1',
    sku: 'PRO-1',
    priceCents: 100,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-2',
    organizationId: '111',
    name: 'Prod 2',
    sku: 'PRO-2',
    priceCents: 100,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-3',
    organizationId: '111',
    name: 'Prod 3',
    sku: 'PRO-3',
    priceCents: 100,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod-4',
    organizationId: '111',
    name: 'Prod 4',
    sku: 'PRO-4',
    priceCents: 100,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const productsWithInventory = [
  {
    id: 'prod-1',
    organizationId: '111',
    name: 'Prod 1',
    sku: 'PRO-1',
    priceCents: 100,
    active: true,
    inventoryLevels: [
      { locationId: 'loc-2', id: 'il-1', quantity: 100 },
      { locationId: 'loc-1', id: 'il-2', quantity: 100 },
    ],
  },
  {
    id: 'prod-2',
    organizationId: '111',
    name: 'Prod 2',
    sku: 'PRO-2',
    priceCents: 100,
    active: true,
    inventoryLevels: [
      { locationId: 'loc-2', id: 'il-1', quantity: 100 },
      { locationId: 'loc-1', id: 'il-2', quantity: 100 },
    ],
  },
  {
    id: 'prod-3',
    organizationId: '111',
    name: 'Prod 3',
    sku: 'PRO-3',
    priceCents: 100,
    active: true,
    inventoryLevels: [{ locationId: 'loc-1', id: 'il-2', quantity: 100 }],
  },
  {
    id: 'prod-4',
    organizationId: '111',
    name: 'Prod 4',
    sku: 'PRO-4',
    priceCents: 100,
    active: true,
    inventoryLevels: [
      { locationId: 'loc-3', id: 'il-3', quantity: 100 },
      { locationId: 'loc-2', id: 'il-1', quantity: 100 },
      { locationId: 'loc-1', id: 'il-2', quantity: 100 },
    ],
  },
];
