/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Database connectivity check
         */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/base": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Base health
         * @description Basic service liveness
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Returns a short-lived access token (JWT), a refresh token, and the user context with memberships.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchanges a valid refresh token for a new access token and returns the current user context.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout current user
         * @description Revokes all active refresh tokens for the current user. Requires a valid access token.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get customers
         * @description List customers for the active organization with pagination.
         */
        get: operations["CustomerController_getCustomers"];
        put?: never;
        /** Create customer */
        post: operations["CustomerController_createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get individual customer */
        get: operations["CustomerController_getCustomerById"];
        put?: never;
        post?: never;
        /** Delete customer */
        delete: operations["CustomerController_deleteCustomer"];
        options?: never;
        head?: never;
        /** Update customer */
        patch: operations["CustomerController_updateCustomer"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get products
         * @description List products for the active organization with pagination.
         */
        get: operations["ProductController_getProducts"];
        put?: never;
        /** Create product */
        post: operations["ProductController_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by ID */
        get: operations["ProductController_getProductById"];
        put?: never;
        post?: never;
        /** Delete product */
        delete: operations["ProductController_deleteProduct"];
        options?: never;
        head?: never;
        /** Update product */
        patch: operations["ProductController_updateProduct"];
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregated inventory
         * @description Returns paginated total quantity per product and breakdown by locations for the active organization.
         */
        get: operations["InventoryController_getInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List inventory levels
         * @description Paginated list of inventory levels with product and location.
         */
        get: operations["InventoryController_getLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create inventory adjustment
         * @description Adjust inventory level for a product at a location. Positive delta restocks; negative delta reduces stock.
         */
        post: operations["InventoryController_createAdjustment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders for an organization
         * @description Paginated list of orders with its items.
         */
        get: operations["OrderController_getOrders"];
        put?: never;
        /** Orders */
        post: operations["OrderController_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/transition-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition the status of an Order */
        post: operations["OrderController_transitionStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Order
         * @description Get an Order by ID
         */
        get: operations["OrderController_getOrder"];
        put?: never;
        post?: never;
        /** Delete Order */
        delete: operations["OrderController_deleteOrder"];
        options?: never;
        head?: never;
        /**
         * Update Order
         * @description Update an Order by ID (metadata only)
         */
        patch: operations["OrderController_updateOrder"];
        trace?: never;
    };
    "/orders/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Order Items
         * @description Adds a new item to an existing order
         */
        post: operations["OrderController_addOrderItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete item from an order
         * @description Delete an item from an existing order
         */
        delete: operations["OrderController_deleteOrderItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshTokenPublicDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UserPublicDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            firstName?: string | null;
            lastName?: string | null;
            isActive: boolean;
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrganizationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MembershipDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            userId: string;
            role: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            organization?: components["schemas"]["OrganizationDto"];
        };
        LoginResponseDto: {
            accessToken: string;
            refreshTokenRaw: string;
            refreshToken: components["schemas"]["RefreshTokenPublicDto"];
            user: components["schemas"]["UserPublicDto"];
            memberships: components["schemas"]["MembershipDto"][];
        };
        RefreshTokenDto: {
            refreshTokenRaw: string;
            /** Format: uuid */
            userId: string;
        };
        RefreshResponseDto: {
            accessToken: string;
            user: components["schemas"]["UserPublicDto"];
        };
        CustomerDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            status: Record<string, never>;
            internalNote: string | null;
        };
        GetCustomersResponseDto: {
            data: components["schemas"]["CustomerDto"][];
            nextCursor?: string;
            totalCount: number;
        };
        CreateCustomerDto: Record<string, never>;
        UpdateCustomerDto: {
            name: string;
            /** Format: email */
            email: string;
            phone: string | null;
            status: Record<string, never>;
            internalNote: string | null;
        };
        ProductDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            category?: string | null;
            sku: string;
            priceCents: number;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GetProductsResponseDto: {
            data: components["schemas"]["ProductDto"][];
            nextCursor?: string;
            totalCount: number;
        };
        InventoryDto: {
            /** Format: uuid */
            locationId: string;
            quantity: number;
            note?: string;
        };
        CreateProductDto: {
            inventory?: components["schemas"]["InventoryDto"];
            name: string;
            sku: string;
            priceCents: number;
            category?: string | null;
        };
        UpdateProductDto: {
            name?: string;
            sku?: string;
            category?: string | null;
            priceCents?: number;
            active?: boolean;
        };
        AggregatedInventoryLocationDto: {
            /** Format: uuid */
            locationId: string;
            quantity: number;
        };
        AggregatedInventoryItemDto: {
            /** Format: uuid */
            productId: string;
            name: string;
            sku: string;
            totalQuantity: number;
            locations: components["schemas"]["AggregatedInventoryLocationDto"][];
        };
        GetAggregatedInventoryResponseDto: {
            data: components["schemas"]["AggregatedInventoryItemDto"][];
            nextCursor?: string;
            totalCount: number;
        };
        LocationDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InventoryLevelsDataDto: {
            product: components["schemas"]["ProductDto"];
            location: components["schemas"]["LocationDto"];
            /** Format: uuid */
            id: string;
            quantity: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        GetInventoryLevelsResponseDto: {
            data: components["schemas"]["InventoryLevelsDataDto"][];
            nextCursor?: string;
            totalCount: number;
        };
        CreateAdjustmentBodyDto: {
            /** @enum {string} */
            reason?: "MANUAL" | "RESTOCK" | "SALE" | "RETURN" | "SHRINKAGE" | "COUNT_CORRECTION" | "INITIAL_STOCK";
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            locationId: string;
            delta: number;
            note?: string;
        };
        InventoryLevelDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            locationId: string;
            quantity: number;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        InventoryAdjustmentDto: {
            /** @enum {string} */
            reason?: "MANUAL" | "RESTOCK" | "SALE" | "RETURN" | "SHRINKAGE" | "COUNT_CORRECTION" | "INITIAL_STOCK";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            locationId: string;
            /** Format: uuid */
            actorUserId?: string;
            delta: number;
            note?: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateAdjustmentResponseDto: {
            inventoryLevel: components["schemas"]["InventoryLevelDto"];
            adjustment: components["schemas"]["InventoryAdjustmentDto"];
        };
        CreateOrderItemDto: {
            /** Format: uuid */
            productId: string;
            qty: number;
            /** @default 0 */
            discountCents: number;
            /** @default 0 */
            taxCents: number;
        };
        CreateOrderDto: {
            orderItems: components["schemas"]["CreateOrderItemDto"][];
            /** Format: uuid */
            customerId?: string | null;
            /** Format: uuid */
            locationId?: string | null;
        };
        OrderItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            productId: string;
            productName: string;
            sku?: string | null;
            qty: number;
            unitPriceCents: number;
            lineSubtotalCents: number;
            /** @default 0 */
            discountCents: number;
            /** @default 0 */
            taxCents: number;
            lineTotalCents: number;
        };
        OrderWithItemsDto: {
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "CANCELLED" | "FULFILLED" | "REFUNDED";
            items: components["schemas"]["OrderItemDto"][];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            customerId?: string | null;
            /** Format: uuid */
            locationId?: string | null;
            subtotalCents: number;
            taxCents: number;
            discountCents: number;
            totalCents: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            placedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
        };
        TransitionStatusBodyDto: {
            /** @enum {string} */
            toStatus: "PENDING" | "CONFIRMED" | "CANCELLED" | "FULFILLED" | "REFUNDED";
        };
        OrderDto: {
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "CANCELLED" | "FULFILLED" | "REFUNDED";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            customerId?: string | null;
            /** Format: uuid */
            locationId?: string | null;
            subtotalCents: number;
            taxCents: number;
            discountCents: number;
            totalCents: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            placedAt?: string | null;
            /** Format: date-time */
            cancelledAt?: string | null;
        };
        UpdateOrderDto: {
            /** Format: uuid */
            customerId?: string | null;
            /** Format: uuid */
            locationId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_getCustomers: {
        parameters: {
            query?: {
                /** @description Max items per page (1-100) */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Sort field */
                sortBy?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetCustomersResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_createCustomer: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate customer or constraint violation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_getCustomerById: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Customer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_deleteCustomer: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Customer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_updateCustomer: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Customer ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Customer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getProducts: {
        parameters: {
            query?: {
                /** @description Max items per page (1-100) */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Sort field */
                sortBy?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProductsResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_createProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate SKU or constraint violation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_getProductById: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_deleteProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductController_updateProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_getInventory: {
        parameters: {
            query?: {
                /** @description Max items per page (1-100) */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Sort field */
                sortBy?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAggregatedInventoryResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_getLevels: {
        parameters: {
            query?: {
                /** @description Max items per page (1-100) */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Sort field */
                sortBy?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
                /** @description Filter by product ID */
                productId?: string;
                /** @description Filter by location ID */
                locationId?: string;
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInventoryLevelsResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InventoryController_createAdjustment: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdjustmentBodyDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAdjustmentResponseDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Attempting to reduce product stock below zero */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_getOrders: {
        parameters: {
            query?: {
                /** @description Filter by status (default ALL) */
                status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "FULFILLED" | "REFUNDED";
                /** @description Include Order Items */
                withItems?: boolean;
                /** @description Max items per page (1-100) */
                limit?: number;
                /** @description Pagination cursor */
                cursor?: string;
                /** @description Sort field */
                sortBy?: string;
                /** @description Sort direction */
                sortOrder?: "asc" | "desc";
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithItemsDto"][];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_createOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithItemsDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_transitionStatus: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionStatusBodyDto"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_getOrder: {
        parameters: {
            query?: {
                /** @description Include Order Items */
                withItems?: boolean;
            };
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_deleteOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_updateOrder: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_addOrderItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Order ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderItemDto"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithItemsDto"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_deleteOrderItem: {
        parameters: {
            query?: never;
            header: {
                /** @description Active organization context for the request. Must be an organization the user is a member of. */
                "X-Organization-Id": string;
            };
            path: {
                /** @description Order ID */
                id: string;
                /** @description Order Item ID */
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderWithItemsDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden (invalid/missing organization context) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
